pub mod steam;
pub mod steam_enhanced;
pub mod steam_enhanced_error;
pub mod epic;
pub mod epic_enhanced;
pub mod gog;
pub mod origin;
pub mod ubisoft;
pub mod battlenet;
pub mod itchio;
pub mod rockstar;
pub mod library;
pub mod games;
pub mod utilities;
pub mod patches;
pub mod injekt;
pub mod anti_cheat;
pub mod performance;
// TEMPORANEAMENTE DISABILITATI PER ERRORI COMPILAZIONE
// pub mod advanced_ocr;
// pub mod translation_backends;
// pub mod offline_translation;
// pub mod translation_logger;
// pub mod low_latency_optimizer;
// pub mod translation_pipeline;
pub mod dlc_manager;
pub mod hltb_manager;
pub mod launcher;
pub mod profile_credentials;
pub mod profiles;
