#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

mod models;
mod commands;
mod cache_manager;
mod error_manager;
mod memory_audit;
mod intelligent_cache;
mod injekt;
mod multi_process_injekt;
mod anti_cheat;
mod performance_optimizer;
mod advanced_ocr;
mod translation_backends;
mod offline_translation;
mod translation_logger;
mod process_utils;

fn main() {
    tauri::Builder::default()
        .manage(commands::anti_cheat::AntiCheatState::default())
        .manage(commands::performance::PerformanceOptimizerState::default())
        .manage(commands::advanced_ocr::AdvancedOCRState::default())
        .manage(commands::translation_backends::TranslationBackendState::default())
        .manage(commands::offline_translation::OfflineTranslationState::default())
        .manage(commands::translation_logger::TranslationLoggerState::default())
        .invoke_handler(tauri::generate_handler![
            commands::steam::auto_detect_steam_config,
            commands::steam::test_steam_connection,
            commands::steam::disconnect_steam,
            commands::steam::get_steam_games,
            commands::steam::fix_steam_id,
            commands::steam::get_game_details,
            commands::steam::get_steam_cover,
            commands::steam::get_steam_covers_batch,
            commands::steam::save_steam_credentials,
            commands::steam::load_steam_credentials,
            commands::steam::clear_steam_credentials,
            commands::steam::save_steam_connection_status,
            commands::steam::load_steam_connection_status,
            commands::steam::remove_steam_credentials,
            commands::steam::auto_connect_steam,
            commands::steam::force_refresh_steam_games,
            commands::steam::debug_steam_api_raw,
            commands::steam::debug_steam_api,
            commands::steam::debug_steam_api_extended,
            commands::steam::debug_steam_profile,
            commands::steam::add_game_to_library,
            commands::steam::get_steam_games_fast,
            commands::steam::get_all_local_steam_games,
            commands::steam::debug_steam_paths,
            commands::steam::test_single_acf,
            commands::steam::parse_shared_config_vdf,
            commands::steam::get_family_sharing_games,
            commands::steam::get_steam_games_with_family_sharing,
            // Steam Enhanced (steamlocate-rs integration)
            commands::steam_enhanced::scan_steam_with_steamlocate,
            commands::steam_enhanced::find_steam_game_by_id,
            commands::steam_enhanced::get_enhanced_steam_info,
            commands::steam_enhanced::test_steamlocate_integration,
            // DLC Management (cross-store)
            commands::dlc_manager::scan_all_dlc,
            commands::dlc_manager::get_game_dlc,
            commands::dlc_manager::get_dlc_statistics,
            // Epic Games Enhanced (repository-based detection)
            commands::epic_enhanced::scan_epic_games_enhanced,
            commands::epic_enhanced::get_epic_game_enhanced,
            commands::epic_enhanced::get_epic_statistics_enhanced,
            // HowLongToBeat (game completion times)
            commands::hltb_manager::search_game_hltb,
            commands::hltb_manager::get_hltb_statistics,
            commands::hltb_manager::cleanup_hltb_cache,
            commands::hltb_manager::search_games_batch_hltb,
            commands::epic::get_epic_game_details,
            commands::epic::get_epic_game_cover,
            commands::epic::get_epic_covers_batch,
            commands::epic::test_epic_connection,
            commands::epic::disconnect_epic,
            commands::epic::clear_epic_cache,
            commands::epic::get_epic_games_web,
            commands::epic::get_epic_games_by_account_id,
            commands::epic::get_epic_games_complete,
            commands::epic::check_legendary_status,
            commands::epic::install_legendary,
            commands::epic::authenticate_legendary,
            commands::epic::save_epic_credentials,
            commands::epic::load_epic_credentials,
            commands::epic::clear_epic_credentials,
            commands::gog::get_gog_game_details,
            commands::gog::search_gog_game,
            commands::gog::get_gog_game_cover,
            commands::gog::get_gog_covers_batch,
            commands::gog::test_gog_connection,
            commands::gog::connect_gog,
            commands::gog::save_gog_credentials,
            commands::gog::load_gog_credentials,
            commands::gog::clear_gog_credentials,
            commands::gog::disconnect_gog,
            commands::origin::test_origin_connection,
            commands::origin::connect_origin,
            commands::origin::save_origin_credentials,
            commands::origin::load_origin_credentials,
            commands::origin::clear_origin_credentials,
            commands::origin::get_origin_game_info,
            commands::origin::get_origin_covers_batch,
            commands::ubisoft::test_ubisoft_connection,
            commands::ubisoft::connect_ubisoft,
            commands::ubisoft::save_ubisoft_credentials,
            commands::ubisoft::load_ubisoft_credentials,
            commands::ubisoft::clear_ubisoft_credentials,
            commands::ubisoft::get_ubisoft_game_info,
            commands::ubisoft::get_ubisoft_covers_batch,
            commands::battlenet::test_battlenet_connection,
            commands::battlenet::connect_battlenet,
            commands::battlenet::save_battlenet_credentials,
            commands::battlenet::load_battlenet_credentials,
            commands::battlenet::clear_battlenet_credentials,
            commands::battlenet::disconnect_battlenet,
            commands::battlenet::get_battlenet_game_info,
            commands::battlenet::get_battlenet_covers_batch,
            commands::itchio::test_itchio_connection,
            commands::itchio::connect_itchio,
            commands::itchio::save_itchio_credentials,
            commands::itchio::load_itchio_credentials,
            commands::itchio::clear_itchio_credentials,
            commands::itchio::get_itchio_game_info,
            commands::itchio::get_itchio_covers_batch,
            commands::rockstar::test_rockstar_connection,
            commands::rockstar::connect_rockstar,
            commands::rockstar::save_rockstar_credentials,
            commands::rockstar::load_rockstar_credentials,
            commands::rockstar::clear_rockstar_credentials,
            commands::rockstar::get_rockstar_game_info,
            commands::rockstar::get_rockstar_covers_batch,
            // Game Launcher System
            commands::launcher::launch_steam_game,
            commands::launcher::launch_epic_game,
            commands::launcher::launch_gog_game,
            commands::launcher::launch_game_direct,
            commands::launcher::launch_game_universal,
            commands::launcher::get_installed_launchers,
            commands::launcher::test_launcher_functionality,
            commands::library::get_library_games,
            commands::library::get_game_path,
            commands::library::read_game_file,
            commands::library::scan_game_files,
            commands::games::get_games,
            commands::games::get_games_fast,
            commands::games::force_refresh_all_games,
            commands::games::get_game_by_id,
            commands::games::scan_games,
            commands::utilities::get_howlongtobeat_info,
            commands::utilities::get_steamgriddb_artwork,
            commands::utilities::get_preferences,
            commands::utilities::update_preferences,
            commands::utilities::clear_cache,
            commands::utilities::get_cache_stats,
            commands::patches::get_patches,
            commands::patches::create_patch,
            commands::patches::update_patch,
            commands::patches::export_patch,
            commands::patches::translate_text,
            commands::patches::get_translation_suggestions,
            commands::patches::export_translations,
            commands::patches::import_translations,
            commands::injekt::start_injection,
            commands::injekt::stop_injection,
            commands::injekt::get_injection_stats,
            commands::injekt::test_injection,
            commands::injekt::get_processes,
            commands::injekt::get_process_info,
            commands::injekt::inject_translation,
            commands::injekt::scan_process_memory,
            // Multi-Process Injection
            commands::injekt::start_multi_process_injection,
            commands::injekt::stop_multi_process_injection,
            commands::injekt::get_multi_process_stats,
            commands::injekt::get_multi_process_active_processes,
            commands::injekt::force_inject_process,
            commands::injekt::list_multi_process_games,
            // Anti-Cheat System
            commands::anti_cheat::detect_anti_cheat_systems,
            commands::anti_cheat::get_anti_cheat_compatibility_strategies,
            commands::anti_cheat::get_anti_cheat_cache_stats,
            commands::anti_cheat::clear_anti_cheat_cache,
            commands::anti_cheat::test_anti_cheat_detection,
            // Performance Optimization
            commands::performance::get_performance_metrics,
            commands::performance::generate_performance_report,
            commands::performance::optimize_hook_application,
            commands::performance::optimize_translation_batch,
            commands::performance::perform_garbage_collection,
            commands::performance::optimize_memory_usage,
            commands::performance::get_optimization_config,
            commands::performance::update_optimization_config,
            commands::performance::test_performance_optimization,
            // Advanced OCR System
            commands::advanced_ocr::process_image_ocr,
            commands::advanced_ocr::batch_process_images_ocr,
            commands::advanced_ocr::get_ocr_performance_metrics,
            commands::advanced_ocr::get_supported_ocr_engines,
            commands::advanced_ocr::get_ocr_config,
            commands::advanced_ocr::update_ocr_config,
            commands::advanced_ocr::test_ocr_engines,
            commands::advanced_ocr::clear_ocr_cache,
            commands::advanced_ocr::get_ml_scoring_info,
            // Translation Backends System
            commands::translation_backends::initialize_translation_backends,
            commands::translation_backends::translate_text,
            commands::translation_backends::translate_batch,
            commands::translation_backends::get_translation_metrics,
            commands::translation_backends::get_backend_status,
            commands::translation_backends::get_supported_languages,
            commands::translation_backends::get_translation_config,
            commands::translation_backends::update_translation_config,
            commands::translation_backends::configure_backend_api_key,
            commands::translation_backends::toggle_backend,
            commands::translation_backends::test_all_backends,
            commands::translation_backends::test_translation_quality,
            commands::translation_backends::clear_translation_cache,
            commands::translation_backends::get_cost_estimation,
            commands::translation_backends::get_cost_optimization_recommendations,
            // Offline Translation System
            commands::offline_translation::initialize_offline_translation,
            commands::offline_translation::translate_offline,
            commands::offline_translation::translate_batch_offline,
            commands::offline_translation::is_language_pair_supported_offline,
            commands::offline_translation::get_available_offline_models,
            commands::offline_translation::download_offline_model,
            commands::offline_translation::remove_offline_model,
            commands::offline_translation::get_offline_translation_stats,
            commands::offline_translation::get_language_pair_support,
            commands::offline_translation::get_offline_translation_config,
            commands::offline_translation::update_offline_translation_config,
            commands::offline_translation::clear_offline_translation_cache,
            commands::offline_translation::cleanup_unused_offline_models,
            commands::offline_translation::preload_popular_offline_models,
            commands::offline_translation::test_offline_translation_quality,
            commands::offline_translation::get_offline_model_metrics,
            commands::offline_translation::get_offline_storage_recommendations,
            // Translation Logger System
            commands::translation_logger::initialize_translation_logger,
            commands::translation_logger::log_translation,
            commands::translation_logger::add_human_feedback,
            commands::translation_logger::add_translation_correction,
            commands::translation_logger::export_translation_logs,
            commands::translation_logger::get_logger_statistics,
            commands::translation_logger::get_translations_for_review,
            commands::translation_logger::generate_quality_report,
            commands::translation_logger::get_logger_config,
            commands::translation_logger::update_logger_config,
            commands::translation_logger::get_supported_export_formats,
            commands::translation_logger::search_translations,
            commands::translation_logger::get_translations_by_game,
            commands::translation_logger::get_translations_by_language_pair,
            commands::translation_logger::get_quality_stats_by_method,
            commands::translation_logger::get_quality_improvement_recommendations,
            commands::translation_logger::cleanup_old_logs,
            // Cache Management
            cache_manager::get_cache_stats,
            cache_manager::clear_cache,
            cache_manager::clear_all_caches,
            cache_manager::optimize_caches,
            // Error Management
            error_manager::get_error_stats,
            error_manager::get_error_suggestions,
            error_manager::cleanup_error_stats,
            // Steam Enhanced Error Management
            commands::steam_enhanced_error::test_steam_error_handling,
            commands::steam_enhanced_error::test_steam_cache_integration,
            commands::steam_enhanced_error::get_steam_error_statistics,
            commands::steam_enhanced_error::get_steam_error_suggestions,
            // Memory Audit System
            memory_audit::get_memory_statistics,
            memory_audit::detect_memory_leaks,
            memory_audit::cleanup_memory,
            memory_audit::generate_memory_report,
            memory_audit::reset_memory_stats,
            memory_audit::get_allocations_by_type,
            // Intelligent Cache System
            intelligent_cache::get_cache_performance_stats,
            intelligent_cache::preload_popular_cache_items,
            intelligent_cache::cleanup_expired_cache,
            intelligent_cache::generate_cache_report
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
